services:
  - type: web
    name: hogayai-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDmyLcPvuYdGCnYhVNpBewAnD3I1_GOkgw
